# Generated by Django 4.2.7 on 2026-07-20 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studio.ingest_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("banner_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "api_key",
                    models.CharField(
                        default=studio.ingest_models._gen_key,
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("tailnet_host", models.CharField(blank=True, max_length=200)),
                ("auto_run_play", models.CharField(blank=True, max_length=60)),
                ("active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FULFILLED", "Fulfilled"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("total_cents", models.IntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stripe_session_id", models.CharField(blank=True, max_length=200)),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("source_url", models.CharField(blank=True, max_length=1000)),
                ("hls_path", models.CharField(blank=True, max_length=1000)),
                ("thumbnail_url", models.CharField(blank=True, max_length=1000)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (free)"),
                            ("MEMBERS", "Members only"),
                            ("TIER", "Specific tier+"),
                        ],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                ("min_tier", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("TRANSCODING", "Transcoding"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="studio.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "unique_together": {("channel", "slug")},
            },
        ),
        migrations.AddField(
            model_name="client",
            name="primary_contact",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("ARTIST", "Artist"),
                    ("GROUP", "Group / Band"),
                    ("LABEL", "Label"),
                    ("NEWS_AGENCY", "News agency"),
                    ("BUSINESS", "Business"),
                    ("CREATOR", "Creator"),
                ],
                default="ARTIST",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="authorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorized_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="auto_post",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="scopes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VideoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.storecustomer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="studio.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical"),
                            ("DIGITAL", "Digital download"),
                            ("TICKET", "Ticket"),
                            ("BUNDLE", "Bundle"),
                        ],
                        default="PHYSICAL",
                        max_length=12,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("stripe_product_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="studio.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_amount_cents", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("recurring", models.BooleanField(default=False)),
                ("interval", models.CharField(blank=True, max_length=10)),
                ("stripe_price_id", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="studio.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_amount_cents", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="studio.order",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.price",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="studio.client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studio.storecustomer",
            ),
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("tier", models.IntegerField(default=1)),
                ("amount_cents", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("interval", models.CharField(default="month", max_length=10)),
                ("perks", models.TextField(blank=True)),
                ("stripe_price_id", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="studio.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past due"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="studio.storecustomer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="studio.membershipplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=12,
                    ),
                ),
                ("stored_path", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="studio.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_format", models.CharField(max_length=40)),
                ("platforms", models.JSONField(default=list)),
                ("auto_post", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_rules",
                        to="studio.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studio.client",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="target_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingest_devices",
                to="studio.project",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="studio.client",
            ),
        ),
        migrations.CreateModel(
            name="PlatformProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("INSTAGRAM", "Instagram"),
                            ("TIKTOK", "TikTok"),
                            ("YOUTUBE", "YouTube"),
                            ("X", "X"),
                            ("FACEBOOK", "Facebook"),
                            ("LINKEDIN", "LinkedIn"),
                            ("THREADS", "Threads"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_hashtags", models.CharField(blank=True, max_length=500)),
                ("posting_cadence", models.CharField(blank=True, max_length=120)),
                ("best_times", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_profiles",
                        to="studio.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "platform")},
            },
        ),
    ]
